### ISSUE TITLE
Need for Migration from 0.13.X to 0.14.X

### ISSUE THREAD

**Issue by malmusfer-hub** [vincanger/coverlettergpt#17]
I appreciate if you could fix this Migration from 0.13.X to 0.14.X problem . so we can read and communicate to data properly

**Comment by nicobts** [comment]
Yes I agree. I wanted to open the same issue as well. I started to work on the migration from 0.13 to 0.14 already but I'm not proficient with WASP at all so maybe asking for support could be the best option in this case.

**Comment by vincanger** [comment]
Merged!
