### ISSUE TITLE
Payment went wrong

### ISSUE THREAD

**Issue by Jornstar** [vincanger/coverlettergpt#3]
Hi Vin, I payed $ 5 this morning for lifetime access of coverlettergpt, and now its asking for $5 again. Can you help me? Thanks in advance . Jorn

**Comment by vincanger** [comment]
Hey,

Thanks so much for your support :)

Sorry about that. it looks like your stripe payment didn't go through and
was refunded. You should receive it in about 5 business days they say

Heads up. I changed the conditions shortly after to 3 months unlimited
access for $4.95. I hope that's not a problem. Go ahead and pay again and
it should work.

Let me know if you have any other issues and sorry for the issue 🙏

-Vince

**Comment by senorpatricio** [comment]
Hi Vin, I also had this issue. I appreciate your help. Thanks!
