### ISSUE TITLE
Other languages supported?

### ISSUE THREAD

**Issue by maplepy** [vincanger/coverlettergpt#7]
Would we be able to use other languages? Say spanish of french for instance? 
If so how would we do it?
If not, are you interested in implementing it with a multichoice selection box or something like that?

Thanks for the website!

**Comment by vincanger** [comment]
I think all it would take to enable languages is to add an option selector for different languages, and then prompt gpt to accept that language and command it to give the output in that language as well. 

Thanks for the idea. If you want to try it out and create a PR for that, that would be great. If not, it might take me some time to get to it....

**Comment by maplepy** [comment]
Sure! I’ll try to see if I have time to draft a PR, no promises though, been pretty busy with school these days :/

I know that GPT can translate something in another language pretty easily, just adding `in french` at the end suffices

**Comment by vincanger** [comment]
@maplepy all languages are now supported. It will now generate a cover letter in whatever langauge you enter the job description in!

**Comment by maplepy** [comment]
lol just when i was looking to make a cover letter! thank you very much!

**Comment by maplepy** [comment]
oh wait you need an account now :(
