### ISSUE TITLE
Error when generating cover letters

### ISSUE THREAD

**Issue by psyl3x** [vincanger/coverlettergpt#8]
I get the below error when trying to generate a cover letter

Request URL: https://coverlettergpt-server-production.up.railway.app/operations/update-cover-letter
Request Method: POST
Status Code: 500 
Remote Address: [104.196.232.237:443](http://104.196.232.237:443/)
Referrer Policy: strict-origin-when-cross-origin

Seems like the OPTIONS call below succeeds but the POST call above fails:

Request URL: https://coverlettergpt-server-production.up.railway.app/operations/update-cover-letter
Request Method: OPTIONS
Status Code: 204 
Remote Address: [104.196.232.237:443](http://104.196.232.237:443/)
Referrer Policy: strict-origin-when-cross-origin

I tried this yesterday as well and was unable to generate.

**Comment by PsSoliman** [comment]
I get the same error
